/* eslint-disable */
// Auto-generated by scripts/fetch_stats.mjs. Do not edit by hand.
// Source: https://harrydaihaolin.github.io/agent-readiness-leaderboard/data/scores.json
import type { Stat } from './stats';

export const stats: Stat[] = [
  { label: 'Repos benchmarked', value: '96+', detail: "on the public leaderboard (as of 2026-05-01)" },
  { label: 'Checks shipped', value: '—', detail: 'YAML rules across all four pillars' },
  { label: 'Median score', value: '71', detail: "across the public sample (as of 2026-05-01)" },
  { label: 'PRs to fix-hint', value: '< 5 min', detail: 'using --json + agent loop' },
];
